### ISSUE TITLE
Build watcher fails to submit images for analysis

### ISSUE THREAD

**Issue by fridex** [thoth-station/build-watcher#201]
**Describe the bug**

```
Traceback (most recent call last):
  File "app.py", line 343, in _submitter
    _do_analyze_build(
  File "app.py", line 216, in _do_analyze_build
    analysis_response = build_analysis(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 102, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 758, in build_analysis
    response = api_instance.post_build(*params)
TypeError: post_build() takes 2 positional arguments but 7 were given

```

**To Reproduce**
1. Deploy and setup build-watcher to a namespace
2. See the error

**Expected behavior**

build-watcher should be able to submit requests to user-api.

**Comment by fridex** [comment]
Fixed.
