### ISSUE TITLE
ModuleNotFoundError for `invectio`, dependency package of thamos.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/build-watcher#48]
**Describe the bug**
The deployment of build-watcher observers the following issue, it is not
able to install the interdependency package `invectio` of  *thamos*.
```
---> Running application from Python script (app.py) ...
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    from thamos.lib import build_analysis
  File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 34, in <module>
    from invectio import gather_library_usage
ModuleNotFoundError: No module named 'invectio'
```

Observation:
- When installed the pipenv environment in the local system, build-watcher has installed the 
 package in `invectio`, the issue only arises in the openshift deployment.
 It could be the issue of setuptools or the pipenv version.

- If we explicitly provide invectio as the requirement for build-watcher, the following error arises in the openshift deployment.
```
[
  'Collecting thamos from git+https://github.com/harshad16/thamos.git@c65207d4a94862098dc71638c766599faac4afa8#egg=thamos',
  '  Cloning https://github.com/harshad16/thamos.git  (to c65207d4a94862098dc71638c766599faac4afa8) to /tmp/pip-build-3bcz55jc/thamos',
  'Requirement already up-to-date: contoml in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: certifi in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: six in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: python_dateutil in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: setuptools in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: urllib3 in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: daiquiri in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: click in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: distro in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: thoth-analyzer in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: yaspin in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: texttable in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: pyyaml in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: requests in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Requirement already up-to-date: termcolor in /opt/app-root/lib/python3.6/site-packages (from thamos)',
  'Collecting invectio (from thamos)',
  'Requirement already up-to-date: pytz in /opt/app-root/lib/python3.6/site-packages (from contoml->thamos)',
  'Requirement already up-to-date: timestamp in /opt/app-root/lib/python3.6/site-packages (from contoml->thamos)',
  'Requirement already up-to-date: iso8601 in /opt/app-root/lib/python3.6/site-packages (from contoml->thamos)',
  'Requirement already up-to-date: strict-rfc3339 in /opt/app-root/lib/python3.6/site-packages (from contoml->thamos)',
  'Requirement already up-to-date: thoth-common in /opt/app-root/lib/python3.6/site-packages (from thoth-analyzer->thamos)',
  'Requirement already up-to-date: delegator.py>=0.1.0 in /opt/app-root/lib/python3.6/site-packages (from thoth-analyzer->thamos)',
  'Requirement already up-to-date: idna<2.9,>=2.5 in /opt/app-root/lib/python3.6/site-packages (from requests->thamos)',
  'Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /opt/app-root/lib/python3.6/site-packages (from requests->thamos)',
  'Requirement already up-to-date: attrs in /opt/app-root/lib/python3.6/site-packages (from invectio->thamos)',
  'Requirement already up-to-date: sentry-sdk in /opt/app-root/lib/python3.6/site-packages (from thoth-common->thoth-analyzer->thamos)',
  'Requirement already up-to-date: rfc5424-logging-handler in /opt/app-root/lib/python3.6/site-packages (from thoth-common->thoth-analyzer->thamos)',
  'Requirement already up-to-date: pexpect>=4.1.0 in /opt/app-root/lib/python3.6/site-packages (from delegator.py>=0.1.0->thoth-analyzer->thamos)',
  'Requirement already up-to-date: tzlocal in /opt/app-root/lib/python3.6/site-packages (from rfc5424-logging-handler->thoth-common->thoth-analyzer->thamos)',
  'Requirement already up-to-date: ptyprocess>=0.5 in /opt/app-root/lib/python3.6/site-packages (from pexpect>=4.1.0->delegator.py>=0.1.0->thoth-analyzer->thamos)',
  'Installing collected packages: invectio, thamos'
][
  pipenv.exceptions.InstallError
]: [
  "Could not find a tag or branch 'c65207d4a94862098dc71638c766599faac4afa8', assuming commit.",
  'Exception:',
  'Traceback (most recent call last):',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main',
  '    status = self.run(options, args)',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run',
  '    prefix=options.prefix_path,',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install',
  '    **kwargs',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install',
  '    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files',
  '    isolated=self.isolated,',
  '  File "/opt/app-root/lib/python3.6/site-packages/pip/wheel.py", line 347, in move_wheel_files',
  '    assert info_dir, "%s .dist-info directory not found" % req',
  'AssertionError: invectio .dist-info directory not found'
]
```

**To Reproduce**
1. Deploy the build-watcher on openshift
2. Click on the log to check the issue  as the deployment would go into a crash loop

**Expected behavior**
Should work flawlessly :)

**Comment by fridex** [comment]
The issue is in old Pipenv which brings old `setuptools` package in the base image. The old setuptools does not support `setup.cfg`. This was addressed in https://github.com/thoth-station/invectio/pull/16. Let's wait for a new release which should fix that - https://github.com/thoth-station/invectio/issues/17.

**Comment by harshad16** [comment]
Thanks @fridex :smile: 
The issue is resolved with https://github.com/thoth-station/invectio/issues/17.
